.TH "arbol.cpp" 3 "Thu Dec 5 2013" "Version Jose johel Rodriguez" "Examen estructuras" \" -*- nroff -*-
.ad l
.nh
.SH NAME
arbol.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T > \fBnodo\fP ()"
.br
.RI "\fIthis class make a object nodo this have a vector of pointers to son of node and use de de class utility to make pair the elements with the weigh and the template value \fP"
.in -1c
.SH "Function Documentation"
.PP 
.SS "template<typename T > class \fBnodo\fP ()"

.PP
this class make a object nodo this have a vector of pointers to son of node and use de de class utility to make pair the elements with the weigh and the template value 
.PP
Definition at line 7 of file arbol\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Examen estructuras from the source code\&.
