.TH "dot.cpp" 3 "Thu Dec 5 2013" "Version Jose johel Rodriguez" "Examen estructuras" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dot.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <ftream>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <string>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "string \fBto_string\fP (int num)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "string to_string (intnum)"

.PP
Definition at line 9 of file dot\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Examen estructuras from the source code\&.
