.TH "mainnodo.cpp" 3 "Thu Dec 5 2013" "Version Jose johel Rodriguez" "Examen estructuras" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mainnodo.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'nodo\&.hpp'\fP
.br
\fC#include <utility>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <cstdlib>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main ()"

.PP
Definition at line 8 of file mainnodo\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Examen estructuras from the source code\&.
