.TH "nodo.cpp" 3 "Thu Dec 5 2013" "Version Jose johel Rodriguez" "Examen estructuras" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nodo.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <utility>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <cstdlib>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBnodo< T, N >\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<class T , class N > void \fBprintpair\fP (const std::pair< T, N > &aimprimir)"
.br
.RI "\fIThis funcion is to print a a pair\&. \fP"
.in -1c
.SH "Function Documentation"
.PP 
.SS "template<class T , class N > void printpair (const std::pair< T, N > &aimprimir)"

.PP
This funcion is to print a a pair\&. \fBParameters:\fP
.RS 4
\fIthis\fP need the pair you have to print 
.RE
.PP

.PP
Definition at line 39 of file nodo\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Examen estructuras from the source code\&.
