.TH "tree< T, N >" 3 "Thu Dec 5 2013" "Version Jose johel Rodriguez" "Examen estructuras" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tree< T, N > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tree\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB~tree\fP ()"
.br
.ti -1c
.RI "void \fBtree\fP (\fBnodo\fP root)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "vector< \fBnodo\fP > \fBnodevect\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class T, class N>class tree< T, N >"

.PP
Definition at line 11 of file tree\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class T , class N > \fBtree\fP< T, N >::~\fBtree\fP ()"

.SS "template<class T , class N > void \fBtree\fP< T, N >::\fBtree\fP (\fBnodo\fProot)"

.SH "Member Data Documentation"
.PP 
.SS "template<class T , class N > vector<\fBnodo\fP> \fBtree\fP< T, N >::nodevect"

.PP
Definition at line 15 of file tree\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Examen estructuras from the source code\&.
