.TH "tree.hpp" 3 "Thu Dec 5 2013" "Version Jose johel Rodriguez" "Examen estructuras" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tree.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <utility>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <cstdlib>\fP
.br
\fC#include 'nodo\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBtree< T, N >\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBtree\fP (\fBnodo\fP root)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void \fBtree\fP (\fBnodo\fProot)"

.PP
Definition at line 22 of file tree\&.hpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Examen estructuras from the source code\&.
